# Use custom format
format = "$all"

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = false

# Replaces the default "❯" symbol in the prompt with "➜"
[character]                             # The name of the module we are configuring is "character"
success_symbol = " [➜](bold green) "     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = " [✗](bold red) "         # The "error_symbol" segment is being set to "➜" with the color "bold red"

# Directory options
[directory]
truncation_length = 8
truncation_symbol = "…/"

# Disable the package module, hiding it from the prompt completely
[package]
format = "via [📦 $version](208 bold) "

##Add the following below the file
[battery]
full_symbol = "🔋"
charging_symbol = "⚡️"
discharging_symbol = "💀"

##The display configuration option is used to define when the battery indicator should be shown (threshold) and what it looks like (style).
[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]  # "bold yellow" style when capacity is between 10% and 30%
threshold = 30
style = "bold yellow"

# How long the command took to run (if greater than the min_time
[cmd_duration]
min_time = 500
format = "underwent [$duration](bold yellow)"

# Docker
[docker_context]
format = "via [🐋 $context](blue bold)"

# Git
[git_branch]
symbol = "🌱 "
truncation_length = 16
truncation_symbol = ""

[git_commit]
commit_hash_length = 7
tag_symbol = "🔖 "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[🍒 PICKING](bold red)"

[git_metrics]
added_style = "bold blue"
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[git_status]
conflicted = "🏳"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
up_to_date = "✓"
untracked = "🤷‍"
stashed = "📦"
modified = "📝"
staged = '[++\($count\)](green)'
renamed = "👅"
deleted = "🗑"

# Hostname
[hostname]
ssh_only = false
format =  "on [$hostname](bold red) "
trim_at = ".companyname.com"
disabled = false

# Lua
[lua]
format = "via [🌕 $version](bold blue) "

# NodeJS
[nodejs]
format = "via [🤖 $version](bold green) "

# Python
[python]
symbol = "🐍 "
pyenv_version_name = true