# Use custom format
# format = "$character"
# right_format = "$all"
format = """
[░▒▓](#a3aed2)\
[  ](bg:#a3aed2 fg:#090c0c)\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
[](fg:#394260 bg:#212736)\
$nodejs\
$rust\
$golang\
$dotnet\
$python\
$rust\
[](fg:#212736 bg:#1d2230)\
$time\
[ ](fg:#1d2230)\
\n$character"""
continuation_prompt = "▶▶"

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = false

# Replaces the default "❯" symbol in the prompt with "➜"
[character]                             # The name of the module we are configuring is "character"
success_symbol = "[▶](bold green) "     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[✗](bold red) "         # The "error_symbol" segment is being set to "➜" with the color "bold red"

# Directory options
[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
read_only = " "

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

# Disable the package module, hiding it from the prompt completely
[package]
format = "[📦 $version](208 bold) "

# How long the command took to run (if greater than the min_time
[cmd_duration]
min_time = 500
format = '\[[⏱ $duration]($style)\]'

#docker_context
[dotnet]
style = "cyan bold"
format = '\[[$symbol($version)(🎯 $tfm)]($style)\]'

# Git
[git_branch]
symbol = " "
truncation_length = 16
truncation_symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_commit]
commit_hash_length = 7
tag_symbol = "🔖 "
style = "bg:#394260"

[git_state]
style = "bg:#394260"
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[🍒 PICKING](bold red)"

[git_metrics]
added_style = "bold blue"
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
up_to_date = "✓"
staged = '[++\($count\)](green)'
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

# NodeJS
[nodejs]
symbol = " "
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

# Python
[python]
symbol = "🐍 "
pyenv_version_name = true
style = "bg:#212736"
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = "ﳑ"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

# Ruby
[ruby]
style = "bg:#212736"
format = '\[[$symbol($version)]($style)\]'

# Time
[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'