# Use custom format
# format = "$character"
# right_format = "$all"
format = "$all"
continuation_prompt = "▶▶"

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = false

# Replaces the default "❯" symbol in the prompt with "➜"
[character]                             # The name of the module we are configuring is "character"
success_symbol = "[▶](bold green) "     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[✗](bold red) "         # The "error_symbol" segment is being set to "➜" with the color "bold red"

# Directory options
[directory]
truncation_length = 8
truncation_symbol = "…/"
read_only = " "

# Disable the package module, hiding it from the prompt completely
[package]
format = "[📦 $version](208 bold) "

# How long the command took to run (if greater than the min_time
[cmd_duration]
min_time = 500
format = '\[[⏱ $duration]($style)\]'

#aws
[aws]
symbol = "  "
style = "cyan bold"
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'

# Azure
[azure]
disabled = false
format = "[$symbol($subscription)]($style)"
symbol = "ﴃ "
style = "blue bold"

# Docker
[docker_context]
format = "via [🐋 $context](blue bold)"

#docker_context
[dotnet]
style = "cyan bold"
format = '\[[$symbol($version)(🎯 $tfm)]($style)\]'

# Git
[git_branch]
symbol = " "
truncation_length = 16
truncation_symbol = ""
style = "purple bold"
format = '([\[$symbol$branch\]]($style))'

[git_commit]
commit_hash_length = 7
tag_symbol = "🔖 "

[git_state]
style = "purple bold"
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[🍒 PICKING](bold red)"

[git_metrics]
added_style = "bold blue"
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[git_status]
conflicted = "🏳"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
up_to_date = "✓"
untracked = "🤷‍"
stashed = "📦"
modified = "📝"
staged = '[++\($count\)](green)'
renamed = "👅"
deleted = "🗑"
style = "red bold"
format = '([\[$all_status$ahead_behind\]]($style))'

# Hostname
[hostname]
ssh_only = false
style = "red bold"
format =  "[$hostname]($style) "
disabled = false

# Lua
[lua]
style = "bold blue"
format = '\[[$symbol($version)]($style)\]'

# NodeJS
[nodejs]
symbol = " "
style = "bold green"
format = '\[[$symbol($version)]($style)\]'

# Python
[python]
symbol = "🐍 "
pyenv_version_name = true
style = "bold green"
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'

# Ruby
[ruby]
style = "bold red"
format = '\[[$symbol($version)]($style)\]'